### ISSUE TITLE
How to run IOS safari using selenium?

### ISSUE THREAD

**Issue by chris1248** [facebook/WebDriverAgent#120]
I've heard this library can be used to replace appium. But the documentation here is quite limited.
We have a bunch of unit tests that target a ruby/rails website (not an app). So we need to target IOS Safari. Anyways, the test suite uses selenium under the hood. Currently we use appium, but it's not very nice, being so undependable. We would like selenium to use this WebDriverAgent to communicate with a simulator or a real device instead.

Is that possible? And if so how?

**Comment by Jonahss** [comment]
Try out appium version 1.5. We've really improved the dependability.

A project called appium-xcuitest-driver uses facebook webdriveragent to automate iOS as well. It adds a bunch of convenience for calling selenium methods, specifically running Safari tests.

**Comment by chris1248** [comment]
Tried out `appium-xcuitest-driver`. It didn't work when I ran `git submodule update`.

**Comment by Jonahss** [comment]
Yeah, someone else had the same problem yesterday. Perhaps @imurchie can
take a look at it?

**Comment by marekcirkos** [comment]
Hey @chris1248.
WebDriverAgent is our replacement for ios-driver so it should work with your selenium client, however we might not be 100% compatible (tho we are open for Pull Requests). We switched to WDA, because we find it more stable and reliable. Also there are two flavours of WDA:
- WebDriverAgent, which works only on simulator by using UIAutomation,
- XCTWebDriverAgent, which uses XCTest and works both on devices and simulators.

Bare in mind that, UIAutomation is deprecated by Apple and so is WDA. We are fully focused on XCTWDA which is still developed to replace WDA.

If you have anymore questions I will be happy to help you :)

**Comment by marekcirkos** [comment]
@chris1248 happy to close issue?

**Comment by bootstraponline** [comment]
Is there a Safari example for XCTWDA? This seems like a common use case.

**Comment by marekcirkos** [comment]
You just start the application by bundleID.

`curl -X POST -H "Content-Type: application/json" -d "{\"desiredCapabilities\":{\"bundleId\":\"com.apple.mobilesafari\"}}" http://[DEVICE_URL]/session/`

**Comment by bootstraponline** [comment]
Thanks!
