### ISSUE TITLE
Safari support broken on master branch

### ISSUE THREAD

**Issue by bootstraponline** [facebook/WebDriverAgent#127]
Safari launches then immediately terminates using Xcode 7.3 iOS 9.3 iPhone 6 Simulator.

> $ xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'platform=iOS Simulator,name=iPhone 6' test
> $ curl -X POST -H "Content-Type: application/json" -d "{\"desiredCapabilities\":{\"bundleId\":\"com.apple.mobilesafari\"}}" http://localhost:8100/session/

I see the same behavior when attempting to automate Safari via the Ruby bindings.

```ruby
# gem install selenium-webdriver
require 'rubygems'
require 'selenium-webdriver'

caps = {"bundleId" => "com.apple.mobilesafari"}
server_url = 'http://localhost:8100/'

# Safari launches then closes
driver = Selenium::WebDriver.for :remote, desired_capabilities: caps, url: server_url
```

If I attempt to use the driver then an exception is raised:

```ruby
> driver.navigate.to "http://google.com"
Selenium::WebDriver::Error::IndexOutOfBoundsError: Unhandled endpoint: /session/1D174704-DA9C-415D-B198-34562B1B8639/url -- http://localhost:8100/ with parameters {
    wildcards =     (
        "session/1D174704-DA9C-415D-B198-34562B1B8639/url"
    );
}
from /Users/bootstraponline/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.0/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok'
```

It'd be great to have a Safari example that demos loading a webpage with any of the existing selenium bindings.

#120

**Comment by bootstraponline** [comment]
I'm guessing we still need [appium-remote-debugger](https://github.com/appium/appium-remote-debugger) to do Safari automation.

**Comment by marekcirkos** [comment]
Actually Safari does not terminate (Check inspector endpoint and you can see that it is running). It goes to home screen due to interference with `[[XCUIDevice sharedDevice] pressButton:XCUIDeviceButtonHome];`, when starting new session. Unfortunately it does not wait till it is finished.

You can add `[[NSRunLoop currentRunLoop] runUntilDate:[NSDate dateWithTimeIntervalSinceNow:2]];` (sleep might work also) right after ButtonHome call and it should prevent it from deactivating Safari.

However we need to find better solution for that issue

**Comment by bootstraponline** [comment]
I think Google figured out [a work around](https://github.com/google/EarlGrey/pull/66/files#diff-7801155cffe1bab63598c462d4ff61f1R40). Have you looked at their code?

**Comment by marekcirkos** [comment]
Thanks! I'll have a look :)

**Comment by marekcirkos** [comment]
Should be fixed by https://github.com/facebook/WebDriverAgent/commit/6b8e2855c3b7564f33ed91cf0154838ac564e341

**Comment by bootstraponline** [comment]
> Should be fixed by 6b8e285

I tested and Safari successfully launches. Unfortunately the webdriver commands such as `driver.navigate.to "http://google.com"` are broken.

It'd be nice if WebDriverAgent had support for automating Safari instead of just launching it.

**Comment by marekcirkos** [comment]
Could you be more precise on what is broken? 
After launching Safari you should be able to navigate through it as if it was tested application.
WDA does not have `navigate.to` command, because it is very app specific, but I guess Appium has some implementation of this method that translates to WDA recognised commands. If something is broken I should be able to help you

**Comment by bootstraponline** [comment]
> Could you be more precise on what is broken?

It's more of a feature request. The ability to automate mobile websites via Safari's [remote debugger protocol](https://github.com/appium/appium-remote-debugger).  `navigate.to` translates to [`Page.navigate`](https://github.com/appium/appium-remote-debugger/blob/e46218d778ba00a9736fff40c9328af8b626ffef/lib/remote-messages.js#L69). [ios-webkit-debug-proxy](https://github.com/google/ios-webkit-debug-proxy) is a similar approach. My understanding is WDA doesn't currently support mobile web automation.

**Comment by bootstraponline** [comment]
Here's the [same `navigate.to` feature in ios-driver](https://github.com/ios-driver/ios-driver/blob/a9744419508d970fbb1ce18e4326cc624b237c8b/server/src/main/java/org/uiautomation/ios/wkrdp/command/Page.java#L25)
