### ISSUE TITLE
Dependencies are not built with Carthage

### ISSUE THREAD

**Issue by frolovs** [facebook/WebDriverAgent#134]
Hello FB team. 

Currently I've trouble building WebDriverAgent's dependencies with Carthage: KissXML, RoutingHTTPServer, peertalk
it looks like dependencies do not have schemes to build with Carthage... (i might be wrong)

here is a build log:

```
carthage bootstrap --platform ios
*** No Cartfile.resolved found, updating dependencies
*** Fetching WebDriverAgent
*** Fetching KissXML
*** Fetching peertalk
*** Fetching RoutingHTTPServer
*** Checking out KissXML at "5.0.3"
*** Checking out RoutingHTTPServer at "v1.0.0"
*** Checking out peertalk at "5a0495a7b7d81b68e25ea1933c755b677cb040da"
*** Checking out WebDriverAgent at "348209dcde6d638876218f35c9a57b71ef4ad013"
*** xcodebuild output can be found in /var/folders/0d/119bm57x58l6c_6ddx46d__00000gn/T/carthage-xcodebuild.5HyiMf.log
*** Skipped building KissXML due to the error:
Dependency "KissXML" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/robbiehanson/KissXML/issues/new
*** Skipped building RoutingHTTPServer due to the error:
Dependency "RoutingHTTPServer" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/mattstevens/RoutingHTTPServer/issues/new
*** Skipped building peertalk due to the error:
Dependency "peertalk" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/rsms/peertalk/issues/new
*** Skipped building WebDriverAgent due to the error:
Dependency "WebDriverAgent" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/facebook/WebDriverAgent/issues/new
```

**Comment by marekcirkos** [comment]
You should be able to build it anyway.

**Comment by marekcirkos** [comment]
Except "WebDriverAgent" has no shared workspace. Let me fix that

**Comment by marekcirkos** [comment]
Just curious, why you plan add WDA to your project?

**Comment by frolovs** [comment]
@marekcirkos it's a bit faster than instruments approach for us, and allows to access other apps, when it is required.

**Comment by marekcirkos** [comment]
Do you use WebDriverAgentRunner directly or link WebDriverAgentLib into your solution?

**Comment by marekcirkos** [comment]
Took a while to get a review. Now it should work. If you have any issues reopen please reopen this issue

**Comment by ataraxia2013** [comment]
*** Skipped building KissXML due to the error:
Dependency "KissXML" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/robbiehanson/KissXML/issues/new
*** Building scheme "OCMock iOS" in OCMock.xcodeproj
*** Skipped building peertalk due to the error:
Dependency "peertalk" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/rsms/peertalk/issues/new
*** Skipped building RoutingHTTPServer due to the error:
Dependency "RoutingHTTPServer" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/mattstevens/RoutingHTTPServer/issues/new

**Comment by marekcirkos** [comment]
It should build WebDriverAgentLib anyway. We build KissXML, RoutingHTTPServer, peer talk with in WebDriverAgent project. I created PR for them to support Carthage, so this warning should stop appearing in the future

**Comment by marekcirkos** [comment]
@ataraxia2013 can you confirm?
