### ISSUE TITLE
How to automate app like whatsapp with WebDriverAgent?

### ISSUE THREAD

**Issue by jeffl3ung** [facebook/WebDriverAgent#148]
I saw Simon gave a WebDriverAgent demo in Selenium Conference 2015. That is awesome.  Can boot several simulators simultaneously and run the test case. We have a app like Whatsup. So we need to boot 2 simulators at least at the same time to test the chat scenario. So I checked the WebDriverAgent and FBSimulatorControl projects, but there are less info for them. So I have couple questions:
1. I know can start agent in test runner. But how to find elements and manipulate? Do I need to involve Selenium? But how Selenium talks to WDA? Could you give me some hints?

2.You know I need to boot several simulators simultaneously. But how to boot in WDA? WDA need to call FBSimulatorControl,right? How WDA works with FBSimulatorControl? 

There are too many questions, hoho. Thanks in advance from China.

**Comment by marekcirkos** [comment]
I am glad it caught your attention :). To briefly answer your questions you might want to:
1) create and boot simulator
2) Install tested application
3) Launch WDA (more about that [here](https://github.com/facebook/WebDriverAgent/wiki/Starting-WebDriverAgent))
All these steps can be accomplished by using FBSimulatorControl either from code or by using `fbsimctl`. For more information check out [FBSimulatorControl](https://github.com/facebook/FBSimulatorControl).

After WDA has started you can start sending HTTP requests in order to find and interact with elements. Some examples using `curl` client can be found in our [wiki](https://github.com/facebook/WebDriverAgent/wiki/Queries).
If you re looking for an existing solution you might want to checkout [Appium](http://appium.io) or any other selenium client as WDA is compliant with selenium WebDriver spec.

I hope this makes it a bit more clear :).

**Comment by jeffl3ung** [comment]
Thanks. This is very helpful.

**Comment by jeffl3ung** [comment]
Could you tell me where I can find WebDriverAgentRunner.xctest? Do you mean WebDriverAgentRunner\UITestingUITests.m?

**Comment by marekcirkos** [comment]
yes

**Comment by jeffl3ung** [comment]
I try to start WDA with this command as follow, but it does not work. Do you know why? I have booted the simulator.
fbsimctl --state=booted launch_xctest //Users/jeff/Git/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m com.apple.mobilesafari --port 8100 --listen

**Comment by marekcirkos** [comment]
`//Users/jeff/Git/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m` Is wrong. It should be path to compiled WebDriverAgentRunner test bundle `WebDriverAgentRunner.xctest`.

**Comment by jeffl3ung** [comment]
Gotcha. Thanks.

**Comment by jeffl3ung** [comment]
I still have 2 questions:
1.Now build success, but *.xctest in products are in red.  Yes, no files are generated. Do you know why?
2.I can boot WDA with other ways. I can launch my test.app , but it quit immediately. But launch safari, will be good. The error is like:
Error Domain=com.facebook.FBSimulatorControl Code=0 "Failed start test manager" UserInfo={NSLocalizedDescription=Failed start test manager, NSUnderlyingError=0x7fb8ee33a6a0 {Error Domain=com.facebook.FBSimulatorControl Code=0 "Failed to re-launch App Launch com.mycom.testApp (test_App)

**Comment by marekcirkos** [comment]
1. UITests are wrapped into test runner application, that contains test bundle as resource. You can check product folder for WebDriverAgentRunner-Runner and look for test bundle inside it. This is because Xcode does not execute UITest bundles directly.
2. There is not much information, if could paste link to device log from that run, that would be more helpful.

**Comment by jeffl3ung** [comment]
1. I can find it in this place: 
/Users/jeff/Library/Developer/Xcode/DerivedData/WebDriverAgent-dvelnmslczgghxcizaevcwmxstcy/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest  
Not this place:
/Users/jeff/Library/Developer/Xcode/DerivedData/WebDriverAgent-dvelnmslczgghxcizaevcwmxstcy/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner.xctest

2.I am wondering if it caused by developer certificate. Because when I launch the app manually , it crashed. This ipa provided by developer, I unzipped it , and install with this command :"fbsimctl 7FBA26B0-222A-4F51-82AB-BBD6E5B324BC install mytest.app"

**Comment by noshuai** [comment]
after running command, http://127.0.0.1:8100/inspector cannot open.
cmd:
./fbsimctl 619DD911-E438-4760-BFFF-BFCECD00C808 launch_xctest /Users/didi/Library/Developer/Xcode/DerivedData/WebDriverAgent-ezggujfqwgoegvemkcaykqqihoul/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest com.apple.mobilesafari --port 8100 --listen
output:
CoreSimulator: Successfully loaded
CoreSimulator: SimDevice has correct path of /Applications/Xcode.app
SimulatorKit: Successfully loaded
SimulatorKit: SimDeviceFramebufferService has correct path of /Applications/Xcode.app
Loaded All Private Frameworks [CoreSimulator, SimulatorKit]
MobileDevice: Successfully loaded
Loaded All Private Frameworks [MobileDevice]
MobileDevice: Successfully loaded
Loaded All Private Frameworks [MobileDevice]
DTXConnectionServices: Successfully loaded
DTXConnectionServices: DTXConnection has correct path of /Applications/Xcode.app
DTXConnectionServices: DTXRemoteInvocationReceipt has correct path of /Applications/Xcode.app
XCTest: Successfully loaded
XCTest: XCTestConfiguration has correct path of /Applications/Xcode.app
Loaded All Private Frameworks [DTXConnectionServices, XCTest]
