### ISSUE TITLE
Coordinate-based clicking and touch events

### ISSUE THREAD

**Issue by mbwPiazza** [facebook/WebDriverAgent#158]
Hey,

I was reading through your documentation, and I was wondering if this project supports clicking or gestures using X and Y coordinates. Is this accomplishable with WebDriverAgent or XCTest private header files?

If so, could you share with me instructions or ideas on how to do so?

Thanks!

**Comment by marekcirkos** [comment]
I am not sure if I understand your use case. How do you plan to use WDA?

**Comment by mbwPiazza** [comment]
Use case 1: I have coordinates, (x=50, y=100), that correspond to a location on the screen. Could WDA be used to click on the element at those coordinates?

Use case 2: I have two sets of coordinates, (x1=50 , y1=100) and (x2=50, y2=200) that correspond to two locations on the screen. Could WDA be used to press down at location 1 and swipe to location 2. Ex) drag and drop an object. Ex2) swipe from left to right.

**Comment by marekcirkos** [comment]
WDA currently supports executing commands via HTTP. Check https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBElementCommands.m#L60 and https://github.com/facebook/WebDriverAgent/blob/master/WebDriverAgentLib/Commands/FBElementCommands.m#L61. 

Also I am working on extracting HTTP handling layer so that people can use WDA as a helper to write their own XCTests, but we are not there yet.
