### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Gogle** [facebook/WebDriverAgent#178]
I write a Monkey test using WDA and come across with this memory issue.
The following statement will cause a memory leak:
```all_elements = [FBFindElementCommands descendantsOfElement:app withClassName:@"XCUIElementTypeAny"]```
If I do it in a for loop, XCTRunner will finally run out of memory and  be killed  by jetsam (iOS system protection when its memory is exhausted).

**Comment by marekcirkos** [comment]
This is nice narrowing of the problem, thanks! I'll have a look.

**Comment by chenhengjie123** [comment]
@Gogle How did you locate this code as memory leak?

I'm facing the same issue, and trying to locate the memory leak code and fix it. But I cannot use instruments to profile. The WebDriverAgentRunner process would be terminated when instruments trying to attach it.

**Comment by marekcirkos** [comment]
I might have found what was the issue here. I landed one [fix](https://github.com/facebook/WebDriverAgent/commit/6a1f18537240698f7b0fb97e4864a3d866025802) and I am waiting for code review of another one. In short querying elements queries Springboard each time creating new `XCUIApplicationProcess` that registers with `XCApplicationMonitor` which breaks process monitoring system. We had different issue where killing application (closing session) took over a minute. I think those issues might be related. 
I would be grateful if you could check this issue when second patch lands. Obviously I'll let you know when that happens.

**Comment by chenhengjie123** [comment]
Since your fix is in master now, I have use it to run my monkey test on iPad Air2 with iOS 9.3 for almost 2 hours. The data is like below:

![image](https://cloud.githubusercontent.com/assets/2800797/16906383/66e18d02-4ce9-11e6-951a-08d66794cc61.png)

I have run same tests before your fix before, **WDA uses 120.5MB memory while it runs for about 6,400 seconds**. It looks this fix improved memory performance, but memory leak still exists.

PS: The monkey I ran would continually send tap and swipe(dragAndDropDuration) random coordinate events to device, and it would find and click element with label "back" each 60 events.

**Comment by marekcirkos** [comment]
Landed second [diff](https://github.com/facebook/WebDriverAgent/commit/c1f949bac3d8d5b3b4ae4d088648cbb27ab97d3c). Keep in mind that if you are using one session to run test for two hours, it is expected for memory to raise as we keep caching queried elements.

**Comment by marekcirkos** [comment]
Can you try killing session or starting new one after that time?

**Comment by Gogle** [comment]
@marekcirkos That isn't work for me. :-( 
I have already noticed WDA keeps caching queried elements.
OK. To clarify the problem with fewer words, I paste some pseudocode here:
```
// Create a new route
[[FBRoute GET:@"/runMonkeyTest"] respondWithTarget:self action:@selector(handleRunMonkeyTest:)]
...
+ (id<FBResponsePayload>)handleRunMonkeyTest:(FBRouteRequest *)request
{
  for (int i = 0; i < 500; i++) {
    NSArray<XCUIElement *> *elements = [FBFindElementCommands descendantsOfElement:request.session.application withClassName:@"XCUIElementTypeAny"];
    // Will randomly choose an element and perform some kind of action on it
  }
  return FBResponseWithOK();
}
```
That's it. Once the selector is invoked, memory will keep increasing dramatically.
It seems that this issue have nothing to do with WDA. Instead XCTest should be blamed for it. However I wonder if there's a solution to this.

**Comment by chenhengjie123** [comment]
@marekcirkos I have tried to kill session while the memory reaches 96MB using DELETE method, it decrease about 20MB memory, but still using 76MB.

**Comment by chenhengjie123** [comment]
Tried to run monkey again with latest code ([48c6b6a](https://github.com/facebook/WebDriverAgent/commit/48c6b6a299d2378c8761753687f75a2d421e32a2)). Result is as below:

1. Continually running monkey events:
![image](https://cloud.githubusercontent.com/assets/2800797/17017166/db378166-4f64-11e6-9e1b-4ca315d3791e.png)

2. Stop session:
![image](https://cloud.githubusercontent.com/assets/2800797/17017174/e16abec2-4f64-11e6-8731-2443ffd0d282.png)

3. Restart session. It's the same as stop session right after starting new session.

**Comment by makhov** [comment]
Looks like memory leak is absent in Xcode 8. Tested on iPhone SE (iOS 10.0) simulator.

**Comment by marekcirkos** [comment]
@chenhengjie123 can you confirm?

**Comment by marekcirkos** [comment]
@Gogle can you confirm?

**Comment by marekcirkos** [comment]
If it is still an issue please reopen.
