### ISSUE TITLE
Improve WebDriver spec compliancy.

### ISSUE THREAD

**Issue by marekcirkos** [facebook/WebDriverAgent#179]
Spec: https://w3c.github.io/webdriver/webdriver-spec.html

We have many custom endpoints that should be changed or reimplemented so that WDA can be used with any WD compliant client. I will create full list of endpoints that needs fixing soon.
- [ ] Click command does not scroll to element

**Comment by chenhengjie123** [comment]
I have found some of it when trying to write my python client base on selenium python client for WebDriverAgent:

1. Get page should use GET method, not POST
2. Error message in return json should be in 'message' argument, not 'value'
3. While getting textfield element's text attribute, return "" instead of null when no text in textfield
4. Use same attribute name in finding strategy and source tree (returned by get source command) for class name. Now in source, its name is 'class', but in finding strategy, its name is 'type'
5. Use same value in finding strategy and source tree (returned by get source command) for class name. For example, it use 'Button' in source tree, but 'XCUIElementTypeButton' in finding strategy.
6. Return element tree as xml format, not json format. Since we have finding strategy 'xpath', returning xml would be better than json.

Hoping this could help you. : )

**Comment by marekcirkos** [comment]
This is awesome, I'll definitely check them with WD spec and add to the list. Thank you

**Comment by chenhengjie123** [comment]
You're welcome : )

It's my pressure that I have contributed my little power to this awesome project.

**Comment by asm89** [comment]
@marekcirkos and I did an initial pass on missing/custom endpoints. Raw notes here: https://gist.github.com/asm89/f8e2227d3e017cf1dd4f54202104ee80. Let's get everything into shape on the endpoint level and then do another pass where we audit all the spec defined endpoints on behavior and response values.

**Comment by marekcirkos** [comment]
@mykola-mokhnach, @imurchie, @asm89. Using WD properties with WDA is becoming more and more confusing. We need to clarify how dow we map `identifier`, `title`, `label`, `value`, `placeholderValue, `selected`, `hasFocus`, `enabled`, `frame` from `XCUIElement` to WD's search strategies. I want to make it in a way that makes sense for FB and other WDA users. Do you have any thought on that?

**Comment by mykola-mokhnach** [comment]
@marekcirkos I think that only properties defined in FBElement protocol should be visible to end user, should be present in source json/xml representation and be available for predicate search (I've just recently created a PR for it). Also I would like to create a second one to represent page source as xml, but after https://github.com/facebook/WebDriverAgent/pull/308 is merged to master.

**Comment by jlipps** [comment]
agree with @mykola-mokhnach. However the actual source XML is less important than WD methods working as expected.

**Comment by marekcirkos** [comment]
@mykola-mokhnach, @jlipps If you compare locators from other servers. They mainly use byId,  byName and byText which works differently on WDA. I was thinking about consolidating wide range of properties on XCTest to those three.

**Comment by marekcirkos** [comment]
I guess we can close it now, we have separate task for removing `byName` and `action interface`. Rest should be resolved
