### ISSUE TITLE
Throw error if an invalid locator selector is used

### ISSUE THREAD

**Issue by Jonahss** [facebook/WebDriverAgent#32]
Seems like right now, a fineElement command will return no elements if you use an invalid locator selector. But it would be more useful if the server threw a `{status: 32, value: "invalid locator requested: ${usingText}"`
https://code.google.com/p/selenium/wiki/JsonWireProtocol#Response_Status_Codes

I think throwing that error in a catchall `else {}` statements (here)[https://github.com/facebook/WebDriverAgent/blob/36326bd1fcea3229314db6d3c4412d4442993dcf/WebDriverAgentLib/WebDriverCommands/FBFindElementCommands.m#L155] would work. Whats the best way of throwing that particular error here?

**Comment by mmmulani** [comment]
@marekcirkos how do we go about raising errors again?

**Comment by marekcirkos** [comment]
There are two approaches you can take. If it is command specific, handle it in command however you think fit. In case more common issues (cross commands)  like elements obstructed by alerts we throw exceptions and handle them in FBWebServer class (to avoid code repetition). Your case looks simple, because you can validate locator selector before using it in `+[FBFindelementCommand elementsUsing:withValue:under:element]`. Validation could be simple as checking if selector is specified by `FBElement` protocol (after transforming it with wdAttributeNameForAttributeName() function).

**Comment by marekcirkos** [comment]
@Jonahss Is this what you were after?

**Comment by Jonahss** [comment]
@marekcirkos Ah close. That one is good too. But I was referring to the locator strategies like:
`link text`
`class name`
`xpath`

The `usingText` parameter from the link below:

https://github.com/facebook/WebDriverAgent/blob/36326bd1fcea3229314db6d3c4412d4442993dcf/WebDriverAgentLib/WebDriverCommands/FBFindElementCommands.m#L151

**Comment by marekcirkos** [comment]
Makes much more sense and will be cheaper ;).
Check out https://github.com/facebook/WebDriverAgent/pull/108

**Comment by Jonahss** [comment]
Looks good :)
