### ISSUE TITLE
Automatically Accepting Alerts

### ISSUE THREAD

**Issue by imurchie** [facebook/WebDriverAgent#335]
Appium has long had the capability to catch and accept alerts a they open. This is functionality that is tremendously useful.

I've found a promising function on XCTestCase (https://developer.apple.com/reference/xctest/xctestcase/1496273-adduiinterruptionmonitorwithdesc?language=objc) but I can't for the life of me get it working, even without trying to wire it to a desired capability.

Any thoughts on how this might work?

**Comment by marekcirkos** [comment]
Why not handle alerts from client? This way you will be dependant on XCTest functionally.

**Comment by jlipps** [comment]
@marekcirkos in some cases there were alerts that might pop up at any point during a test run, which made it impossible to deterministically handle them.

**Comment by marekcirkos** [comment]
You can always handle that on client when you are about to fail. Check if alert is present, dismiss and retry.

**Comment by imurchie** [comment]
That would be the last resort, and a rather heavy-handed one.

**Comment by marekcirkos** [comment]
XCTest handler probably will not work because I think they depend and errors/exceptions being thrown by XCTest, which we explicitly prevent. 

I don't want to add and complicated logic to WDA as I think it should be as simple as possible. This way it is easier to get it replaced if needed. Also it is hard to satisfy all client needs. Best example of it is scrollToVisible, where we had a lot of discussions how it should work. In my opinion it should be handled by client as it has best knowledge about context of scrolling. Exactly same problem will raise with alert handling as some might not want to do that or/and want to test alert presence etc.

**Comment by marekcirkos** [comment]
@imurchie  ?

**Comment by imurchie** [comment]
This remains a desideratum, and is not easily done at our end. Honestly I haven't had time to investigate much. I guess it can be closed if the Apple-provided means does not work. :(

**Comment by marekcirkos** [comment]
Apple ways work with system alerts not sure if it will work with app alerts.

**Comment by marekcirkos** [comment]
But we should check.

**Comment by ohadschn** [comment]
If this turns out to be possible, providing some hooks into this behavior as to allow the user to decide whether to intercept the alert or not, would be great. This, as opposed to blindly dismissing all alerts, some of which I might expect and want to handle in some specific manner on my own.

In other words, have a hook that provides me with some information on the alert (e.g. title, text, buttons text) and allow me to decide whether I want to let appium handle it automatically, or handle it myself manually (in my test code). That way I can handle alerts I expect, and let Appium handle alerts I don't expect (like OS upgrade) that would have otherwise broken my test.

**Comment by interhealth** [comment]
It appears the issue of alertAccept() not working in iOS has not be solved.
Anyone have any leads to a workaround?
Thank you

**Comment by VenkateshPS** [comment]
When is this expected to be fixed?

Regards
Venkatesh

**Comment by marekcirkos** [comment]
So far we do not plan to work on auto accepting alerts. Tho, feel free to pop a PR, if you want to do it
