### ISSUE TITLE
feasibility of double-pressing home screen?

### ISSUE THREAD

**Issue by jlipps** [facebook/WebDriverAgent#461]
Hi @marekcirkos, I see that in a few places in WDA we do something like this:

```objc
[self pressButton:XCUIDeviceButtonHome];
```

Is there any reason we couldn't call it twice (maybe with a small delay), to bring up the app switcher? Something like:

```objc
[self pressButton:XCUIDeviceButtonHome];
[[NSRunLoop currentRunLoop] runUntilDate:[NSDate dateWithTimeIntervalSinceNow:0.3]];
[self pressButton:XCUIDeviceButtonHome];
```

Let me know, I'm happy to draft a PR

**Comment by marekcirkos** [comment]
You care about switcher or homescreen. We do have `/wda/homescreen` endpoint. 
I you care about switcher, this might not be enough. Do we even care about delay?

**Comment by jlipps** [comment]
Yeah, I care about getting to the switcher. Maybe we don't need a delay. Just playing around with my simulator, if I pressed `cmd+shift+H` too fast, the switcher didn't come up. I'm just speculating maybe there is a sweet spot of how fast to emulate the press.

**Comment by marekcirkos** [comment]
We could introduce `/wda/appswitch` endpoint. Timing on pressing home button is tricky. You can check deactivate app endpoint for some ideas. However navigating through app switch would be tricky, I guess.

I assume you want this to resume to the different app? Maybe it would be better to have `/wda/activate/:app` or whatever endpoint that does that possibly in different way? We kind of do this with `/wda/deactivate`. We go to homescreen, wait and resume app. There is some API that you might find useful already. Unless you really care about app switch.

**Comment by jlipps** [comment]
I know @midopa was interested in this feature. @midopa would you rather have something that just gets you to the app switcher? Or something that actually switches to an app given an appropriate ID? I'm not sure what's technically feasible or what elements you actually have control over with the app switcher.

**Comment by midopa** [comment]
Sorry, I should've brought this up sooner. For me, the app switcher isn't as much of a concern anymore. I don't need it as much as I need the existing home screen endpoint exposed in Appium.

The main goal is cross-app automation.

It would be great if you can provide a way to switch apps deterministically and by normal user means (ie. not launching the app through XC Test because this may skip app lifecycle events that may need to be tested). If not, then I have everything I need with the home screen action.

<details>
<summary>The Many Words Section</summary>

The app switcher approach was an attempt to optimize test runs. Instead of going home, swiping across home pages, and tapping on the app's icon, you can just open the app switcher and tap on the app's window. But it turns out to be fragile.

The app switcher renders several app windows at once that obscure each other. They're all marked as "visible". The default click action taps on the center of the element's bounds. If the app window is obscured, the click will go somewhere else. So you have to: 1. Make sure the app you want is either at the top, or clearly visible. 2. Tap on the top left corner of the window 

At this point, it's just simpler and more reliable to use the home-swipe-app approach.
</details>

**Comment by jlipps** [comment]
Oh great feedback @midopa. So it sounds like the most reliable way to switch apps is just to go to the homescreen and navigate the UI to find the other apps from there. I'm happy to close this then if @marekcirkos wants, as I think you were the originator of this request on the Appium side :-)

**Comment by jochasinga** [comment]
@marekcirkos if possible I'd like this reopened. I am interested in specifically going to the app switcher. Either by mean of using the XCUIDevice's API directly or any other. 

I've been working on the `/wda/appswitcher` but as you commented ![here](https://github.com/facebook/WebDriverAgent/blob/0243c1cfeb80dfadb649f8e18969ead0a0b50dae/WebDriverAgentLib/Categories/XCUIDevice%2BFBHelpers.m#L28-L32) the first press is asynchronous and always leads to homescreen ignoring the second subsequent press.

**Comment by shubhankaryash** [comment]
Does calling the Home press twice with a slight delay even work. I am trying this but i don't see this working.

**Comment by jochasinga** [comment]
No it does not. At least for me. The homepress call is asynchronous and may even be executed in a separate thread. The subsequent calls tried on varied delays we're meaningless.
