### ISSUE TITLE
UITableView issue

### ISSUE THREAD

**Issue by PradeshKumar-emisweb** [facebook/WebDriverAgent#471]
I'm testing an scenario to verify the cell values for `UITableView` in appium. Appium provides the correct values for the visible cells, but incorrect values for the invisible cell.

For eg., A table is having 30 rows, 20 is visible and 10 is not visible. The table returned to the tests has the top 20 ones correct. The last 10 has the same information as the 30th row.

Do we have any work around for this issue?

**Comment by marekcirkos** [comment]
@PradeshKumar-emisweb Invisible cells do not work well with XCTest. Sometimes they contain trash informations. Best strategy is to relay test on visible elements and ignore invisible ones.

**Comment by christoff-1992** [comment]
Agreed, what about static tables where content is offscreen. If we use the workaround for #466 the cell's won't be included as there outside the visible frame.

Is it best to use the scroll method, or is there a way of excluding tables from the check when getting the page source, so the entire table is included in the page source?

Thanks.

**Comment by marekcirkos** [comment]
@christoff-1992 I am not sure what do you mean.

**Comment by christoff-1992** [comment]
Apologies I should have gone into greater detail, this issue is only persistent with long tables using the workaround in #466, which is needed as it stops the 'Error Domain=XCTestManagerErrorDomain Code=13 "Error copying attributes -25202"' issue.

handleFindVisibleCells checks the visibility of the Cells via fb_isVisible.

However if you where to use the workaround in #466 anything outside of the visible frame is excluded.

This means any cells that exist but are currently outside of the frame are not included in the tree of elements.

**Comment by marekcirkos** [comment]
That is true and it goes as expected since this is `getVisibleCells` endpoint right?

**Comment by christoff-1992** [comment]
Indeed this is the expected behaviour for this method when using the workaround.
Im not sure if this should be the case, it's a 50/50 handoff, in one way it's good that it resolves the -25202 but bad that it hides the cell's when they do exist off screen.

I have added a separate method locally that uses the current behaviour of fb_isVisible for handleFindVisibleCells, so I can have the best of both world's but don't like doing this. Once I get some time il have a look at a better approach to this. But is this something worth adding to the review for #466 ?

**Comment by marekcirkos** [comment]
@christoff-1992 I reimplemented visibility check, can you check if it improved your situation?

**Comment by christoff-1992** [comment]
@marekcirkos oo thank you will take a look shortly and update :)

**Comment by christoff-1992** [comment]
This seams to be working :) Thank you @marekcirkos

**Comment by wsndy163** [comment]
https://github.com/wsndy163/WebDriverAgent
修复swipe引起的列表卡顿问题
