### ISSUE TITLE
Enqueue Failure: UI Testing Failure - Failed to get snapshot within 15.0s

### ISSUE THREAD

**Issue by amleszk** [facebook/WebDriverAgent#474]
Copied from appium project: https://github.com/appium/appium/issues/7796

## The problem

Error finding elements

`XCTRunner[83980:8602143] Enqueue Failure: UI Testing Failure - Failed to get snapshot within 15.0s /usr/local/lib/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 35 1`

## Environment

* Appium version (or git revision) that exhibits the issue: Appium `1.6.3` and Appium `1.6.4-beta`
* Last Appium version that did not exhibit the issue (if applicable): `1.6.4-beta`
* Desktop OS/version used to run Appium: OSX 10.11.5 (15F34) El Capitan
* Node.js version (unless using Appium.app|exe): v6.2.1
* Mobile platform/version under test: iOS Simulator 10.1
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: CLI

## Details

Appium will hang and not perform any actions, this error appears randomly

## Link to Appium logs

https://gist.github.com/amleszk/1c4ef4c75227f23b3cbee7ba4865b6ca

**Comment by marekcirkos** [comment]
Is it possible that app crashed or deadlocked?

**Comment by amleszk** [comment]
@marekcirkos The app does become unresponsive when the errors start happening, but I don't think it's from deadlocking on the app side. I noticed this happens when there are a lot of UI elements on screen. I can't share the project because it's a closed source app

**Comment by wangtao169447** [comment]
@amleszk 
https://github.com/appium/appium/issues/7641
have a try?

**Comment by mykola-mokhnach** [comment]
@amleszk We had a similar issue when a CollectionView was constantly updated due to "hacky" implementation. XCUIElement instances (this is the main class, which XCTest uses to represent accessibility controls) are automatically updated every time when app interface is updated. So the XCTest framework simply cannot properly receive the accessibility structure of the app, since it's constantly being updated by the app and therefore raises such error.

[Here](https://github.com/wireapp/wire-ios/commit/5bb787b82c93ab675f4c43471f457bf7a2c900ce#diff-8ef41015046c0abf5c7336ac214dcf0fR146) you can see how the issue was fixed for our app.

**Comment by amleszk** [comment]
Thanks @mykola-mokhnach - Doesnt seem to be a solidly reproducible issue right now, but what you said about the the Appium DOM constantly updating seems like a good lead. Thanks for feedback also @wangtao169447
