### ISSUE TITLE
How to disable the "diagnostic log" created by the xcodebuild when launching WebDriverAgent?

### ISSUE THREAD

**Issue by vslobotskoy** [facebook/WebDriverAgent#488]
Each time I launch WebDriverAgent with xcodebuild command, there is a message like this:
IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/qfactor/WebDriverAgent/DerivedData/WebDriverAgent/Logs/Test/356163F6-32E2-4A39-8CF7-96CADEDA17EC/Session-WebDriverAgentRunner-2017-02-14_193721-04LwDr.log

I use the following command to launch xcodebuild:
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner  -destination 'platform=iOS,id=dxxxxxxxxxxxxxxxxxxxx8' -quiet test

I noticed that during the overnight test runs the log file may accumulate huge amount of messages (100s of megabytes), most of them are like this: 
(LOG ARBITER) Discarding message, buffer is full
These messages are filling the log and as they are spewed once overy 1-3 milliseconds.

Is there a way to disable this "diagnostic log" ? It is pretty much useless to me, and probably slows down execution considerably.

**Comment by marekcirkos** [comment]
I am not sure if xcodebuild has specific switch for that, but you can always redirect outputs to /dev/null right?

**Comment by vslobotskoy** [comment]
This is not the standard output of the xcodebuild, it is something it sends from within.

**Comment by imurchie** [comment]
We change the permissions on the specific folders within DerivedData, so xcodebuild can't write to it.

**Comment by mykola-mokhnach** [comment]
@vslobotskoy this is an expected behaviour if you set _preventWDAAttachments_ Appium capability to _true_. You may reset permissions to DerivedData folder manually and set _clearSystemFiles_ capability to _true_ to clean up these files on session termination.

Unfortunately XCTest framework does not provide any standard interfaces to disable attachments creation and partition flooding, so we need to use such a "dirty" workaround.

@marekcirkos I think we can close the issue.
