### ISSUE TITLE
How to stop screenshot 

### ISSUE THREAD

**Issue by swccc** [facebook/WebDriverAgent#622]
I want no screenshot after WebDriver commands
I see Making screenshot of Real Device

route :  
/Users/mac0516/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Attatchments/

Screenshot~~~~.png 
Screenshot~~~~.png 
Screenshot~~~~.png 
Screenshot~~~~.png 

I won't this files.
how to stop this device screenshot files?

because : I develop bank app . I think that process has delay time

**Comment by mykola-mokhnach** [comment]
Apple does not provide any interfaces in XCTest to control this behaviour, so all this stuff is created independently of whether one wants it or not (probably, it will be fixed in iOS 11). For now one can simply remove write permissions to this folder from the current user to stop XCTest from saving screenshots there.

**Comment by marekcirkos** [comment]
I would assume that there is some intern BOOL that controls that behaviour, so If someone feels like could spend some time with hooper. 
If that is not true probably we would need to re-write some parts of XCTest to change that, which I wouldn't be willing to do :)

**Comment by marekcirkos** [comment]
It is possible to do with Xcode beta! https://github.com/facebook/WebDriverAgent/commit/7e1b4567f39eb2d6da68f90427293c263d7171ff
