### ISSUE TITLE
Physical device support

### ISSUE THREAD

**Issue by bootstraponline** [facebook/WebDriverAgent#7]
It'd be nice to support automation on physical iOS devices.

**Comment by lawrencelomax** [comment]
We've recently attempted this and it looks like the answer to this is a no-go when linking `UIAutomation.framework` to a Singable iOS Application.

When `WebDriverAgent` is sandboxed within an Device Application, rather than as a daemonized simulator binary, it looks like the `UIATarget` commands will error with the "Make sure you have enabled automation on your device" error. This makes some sense if the Framework is requesting some resources from a lower level of the OS and the access to these resources is denied. I'm not that familiar with the architecture, but it probably has to hit `backboardd` in order to get information about the accessibility hierarchy.

The way forward will more than likely be running the `WebDriverAgent` web server inside the xctest loader that gets bundled alongside the App-Under-Test in the new-in-Xcode7 ` UITesting for XCTest API. The agent can then call the appropriate methods and classes on the (public) `XCTest` framework. There are a number of limitations currently with XCTUI testing, but we will need to start with the groundwork, since it's possible that `UIAutomation` is going away in the next major Xcode release.

**Comment by bootstraponline** [comment]
Good to know.

I found this quote from Apple about UIAutomation.

> The old UI Automation support in Instruments is deprecated. UI testing in XCTest is the replacement, and where our efforts will be focused going forward.
> https://forums.developer.apple.com/thread/9169

**Comment by yaphatak** [comment]
Few months back, I made an attempt to run UIAutomation.framework on real device and I got same error that lawrence got. @bootstraponline , same thread says XCUITest is built on top of UIAutomator and if not , most probably built on accessibility concept. So I am not sure we will be able to run XCUI test on device.

**Comment by lawrencelomax** [comment]
XCUITest is not built on top of `UIAutomation.framework` (see the forum thread that @bootstraponline linked to).

I don't see any reason that a Test Target that imports `XCTest` couldn't have the WebDriverAgent webserver with `XCUI*` implementations of the current UIAutomation ways of interacting with the App's UI.

**Comment by bootstraponline** [comment]
XCUITest works on device.

**Comment by Jonahss** [comment]
XCUITests branch seems to be working on real devices ^.^

**Comment by marekcirkos** [comment]
Just merged XCUITest branch. You can use XCTWebDriverAgent to run tests on devices.

**Comment by bootstraponline** [comment]
Awesome.

**Comment by yaphatak** [comment]
Awesome

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Thu, Nov 12, 2015 at 6:06 AM -0800, "Marek Cirkos" <notifications@github.com<mailto:notifications@github.com>> wrote:


Just merged XCUITest branch. You can use XCTWebDriverAgent to run tests on devices.

-
