### ISSUE TITLE
iOS 10.x + Appium 1.7.0beta + iPhone SE PageSource has error value 'AX error -25205' for some attribute values

### ISSUE THREAD

**Issue by rajfidel** [facebook/WebDriverAgent#703]
## The problem

PageSource has issues on iPhone SE + Appium 1.7.0 beta + iOS 10.x. It displays some of the values as 'AX error -25205'
Non-iPhone SE + iOS 11 + Appium 1.7.0 beta works fine. 
Couldn't check iPhone SE with iOS 11 since I do not have a device with this configuration to check.
iPhone SE + Appium 1.6.5 + iOS 10.x works fine as well.

## Logs

The following logs were captured on the iOS Settings app (com.apple.Preferences)

### On Appium 1.7.0 beta

iPhone 6s, Appium Logs [here](https://gist.github.com/rajfidel/6e97801e8281b799c20ddea7f5fb8f03), Page Source [here](https://gist.github.com/rajfidel/f8eea115ec8e4168b4e62785901f637f)
iPhone SE, Appium Logs [here](https://gist.github.com/rajfidel/476dbd829ff3cc07b55b3b0327987935), Page Source [here](https://gist.github.com/rajfidel/c83a080e985a2f70ea8bee4d75277eb2)
**Confirmed on another iPhone SE as well to be the same case.**

From the above logs can be seen that only iPhone SE exhibits this issue with Appium 1.7.0 beta.

### On Appium 1.6.5

iPhone SE, Appium Logs [here](https://gist.github.com/rajfidel/21cff8fdf4699fa22140833efa456748), Page Source [here](https://gist.github.com/rajfidel/1b5b929739b83c701acd56bb61e7d183)

From the above logs can be seen that iPhone SE does not exhibit this issue with Appium 1.6.5

## Environment

* Appium version (or git revision) that exhibits the issue: 1.7.0 beta
* Last Appium version that did not exhibit the issue (if applicable): 1.6.5
* Desktop OS/version used to run Appium: macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe): 8.1.4
* Mobile platform/version under test: 10.2.1
* Real device or emulator/simulator: Real device
* Appium CLI or Appium.app|exe: Appium CLI

**Comment by broven** [comment]
any update? same problem

**Comment by huaius** [comment]
Same here, but only happens on iPad, iOS9 and iOS10
Appium1.7.1 + Xcode9

**Comment by seavan** [comment]
I had the same problem. The solution is to use iOS 11 with XCode 9, for now.

**Comment by spv007** [comment]
Am also facing the same issue with iPad Air + iOS 11 + XCode 9 + Appium 1.7.1

(It works fine with iPhone 6 Plus though, along with the above config. Issue observed with iPads only)

**Comment by JasonArm** [comment]
+1 - I'm running iPhone 5 + iOS 9.2.1 + XCode 9 + Appium 1.7.1

**Comment by kdthomas2121** [comment]
Occurs for every element for me. Iphone 5, iOS 11.0, Appium 1.7.1. Was working fine earlier today, now loading the exact same app with the same conditions in the inspector results in <XCUIElementTypeOther name="AX error -25205">

**Comment by JasonArm** [comment]
Also, +1 - on iPhone 6 + iOS 10.1.1 + XCode 9 + Appium 1.7.1

**Comment by niclaforge** [comment]
any update? same problem

**Comment by Seijan** [comment]
I have the same issue with an IPhone SE 11.0,10.0 + Appium 1.7.1 and as well on an IPhone 8 11.0 + Appium 1.7.1, so any help would be appriciated

**Comment by marekcirkos** [comment]
Is this same issue as in https://github.com/facebook/WebDriverAgent/issues/372?

**Comment by darkmanno6** [comment]
+1 - I'm running iPhone 6p + iOS 10.3.3 + XCode 9 + Appium 1.7.1

**Comment by rakeshsukla53** [comment]
Facing the same issue. Any updates yet  ?

**Comment by rakeshsukla53** [comment]
[UPDATE] : - This issue is resolved after updating to  `iOS 10.3` simulator

**Comment by kdthomas2121** [comment]
Still not resolved when using real devices

**Comment by LakshminarayananG** [comment]
Have upgraded the IOS version to 11 in IPhone 6 and it works fine. Able to inspect the elements.

**Comment by gargvishal** [comment]
+1, faced the same issue.
Upgraded the IOS version to 11 in IPhone 6 and it works fine. Able to inspect the elements.
The XCode version used is 9.X

**Comment by appiumnovice** [comment]
Pb on iPhone 10.2.1 / XCode 9.
I need to automate tests on real devices from iOS 9 to 11.

**Comment by kdthomas2121** [comment]
Testobject free devices are running iOS 9, so I need to automate for 9 also

**Comment by jamesoram** [comment]
I am seeing this issue using Appium 1.7.1, iOS 11.1 and XCode 9.1. All elements appear to have an error code.

**Comment by levyshachar2** [comment]
any update regarding this issue?

**Comment by sdanerib** [comment]
Hi guys, I'm having exact same issue, do you have any update?
I'm working with XCode 9.1, Appium 1.7.1, iPhone 6s with iOS 10.2
<img width="784" alt="screen shot 2017-11-19 at 22 00 21" src="https://user-images.githubusercontent.com/4007648/33000356-84ee0d8a-cd75-11e7-9635-a298375ca6bf.png">

**Comment by sdanerib** [comment]
If this helps anyone, I'm not having issues when trying with:
I'm working with **XCode 9.1**, **Appium 1.7.1**, **Appium Desktop 1.2.5**  and **iPhone 6s or X with iOS 11.1** 😃

**Comment by dilsreccse** [comment]
Any update on this issue, multiple scenarios are getting failed coz of this

**Comment by ashwinibaisutrave** [comment]
I am also facing the same issue with below configuration 
Appium 1.2.6 desktop 
iPhone Simulator 5s
Xcode 9.1 -OS 10.0

**Comment by jmei08** [comment]
facing the same issue using the latest wda + xcode9.1 + ios9/ios10 
@mykola-mokhnach could you had a look at this problem? Thanks.

**Comment by sasasa42** [comment]
This is an issue for me as well on all iOS device below 11. @mykola-mokhnach Please help us resolve this issue.

**Comment by Kitty2014** [comment]
iOS 9.3.5 also met

**Comment by bhavikviks** [comment]
@marekcirkos are we releasing the solution to this problem soon?

**Comment by dcnt** [comment]
iPod 6, iOS 10.1:
with XCode 9.x there're 'AX error -25205' in almost all elements.
with XCode 8.x - everything works just fine. So I keep 2 XCodes (8 and 9) for iOS 10 and 11 respectively.

**Comment by jmei08** [comment]
Using xcode9.x + ios11.x with iPhone7Plus，It takes a very long time in the snapshot accessibility hierarchy for app and returns nothing. 
[AXValidations] UIAccessibility Error adding -[CAMLightingControl accessibilityLabel]

**Comment by jeremygenbook2** [comment]
Hi Everyone, 

Any update on this issue yet ?

**Comment by sl1991** [comment]
Hi All,
   Who does solve the issue?

**Comment by SamyQAZ** [comment]
Hi all, I am also facing the same issue with real device iPhone 7 plus iOS 10.2.1, Xcode Version 9.2 and appium.app Version 1.2.7.

Anyone found solution or work around for it?

<img width="1067" alt="screen shot 2017-12-29 at 3 42 35 pm" src="https://user-images.githubusercontent.com/30425316/34432723-1181ca62-ecb5-11e7-811f-4010a17cea5d.png">

**Comment by olyv** [comment]
The only working combination for me is Xcode 9.2 + iOS simulator version platform 11.2

**Comment by Kitty2014** [comment]
should use xcode 8.3.3

**Comment by mykola-mokhnach** [comment]
Try the patch https://github.com/appium/WebDriverAgent/pull/31, which is going to be merged to Appium beta soon

**Comment by SamyQAZ** [comment]
@mykola-mokhnach When will it be available to try?

**Comment by peritus** [comment]
Added the following as a `postinstall` script to my automation project:

```
#!/bin/bash

rm -fr WebDriverAgent-window_based_xml_source
rm -f WebDriverAgent_window_based_xml_source.zip

curl https://codeload.github.com/appium/WebDriverAgent/zip/window_based_xml_source > WebDriverAgent_window_based_xml_source.zip
unzip WebDriverAgent_window_based_xml_source.zip -d WebDriverAgent-window_based_xml_source

for webdrivercopy in `find node_modules|grep WebDriverAgent$`; do
  echo rm -rv $webdrivercopy
  echo cp -rv WebDriverAgent-window_based_xml_source/WebDriverAgent-window_based_xml_source $webdrivercopy
done
```

to use https://github.com/appium/WebDriverAgent/pull/31 ..

**Comment by peritus** [comment]
@mykola-mokhnach Thank you for the update on this one!

Doing so (believe i'm using xcode 9.2 + ios9.3 + appium 1.7.1 + https://github.com/appium/WebDriverAgent/pull/31/commits/e88a6c7ca31cbf52f14b0c6e603d6fdb79ba0a57 as described above) my tests start working again, except for:

### iOS 9.3 + iPhone 6 simulator

When the app asks for camera permissions using the system dialog, i'm still seeing `AX error -25205`. All other ui elements can be found (again! thank you!).

### iOS 11 + iPhone X simulator:

is there an upper limit on the maximum depth of the xml tree building ? I'm seeing

```
                          <XCUIElementTypeOther type="XCUIElementTypeOther" name=" Willkommen zurück!  Login.email   Login.password  Login.forgotPassword   Login.button[disabled]" label=" Willkommen zurück!  Login.email   Login.password  Login.forgotPassword   Login.button[disabled]" enabled="true" visible="true" x="0" y="88" width="375" height="724">
                            <XCUIElementTypeOther type="XCUIElementTypeOther" name="Login.button[disabled]" label="Login.button[disabled]" enabled="true" visible="true" x="0" y="471" width="375" height="50">
                              <XCUIElementTypeOther type="XCUIElementTypeOther" name="Login.button[disabled]" label="Login.button[disabled]" enabled="true" visible="true" x="0" y="471" width="375" height="50"/>
                            </XCUIElementTypeOther>
                          </XCUIElementTypeOther>
                        </XCUIElementTypeOther>
```

but no text input with `name="Login.email" label="Login.email"` :(

..
..

Is this the right place to report this ? Happy to help debugging, let me know how.

**Comment by mykola-mokhnach** [comment]
Thanks for reporting this @peritus. Currently I have no solutions for the problems above.

> is there an upper limit on the maximum depth of the xml tree building

No, there is no limit. We display everything we can get from XCTest.

> but no text input with name="Login.email" label="Login.email"

Is this input present on other iOS versions? Perhaps, your AUT code just does not define these elements as accessible properly.

**Comment by SamyQAZ** [comment]
Updated to Appium CLI - 1.7.2 and appium.app to 1.3.0 still the above issue exist. 
Cannot interact with UI elements. Throws 'AX error -25205'.

Did anyone tried to upgrade to new version and check this issue?

**Comment by peritus** [comment]
@mykola-mokhnach as for the iPhone 6 + iOS9.3 case mentioned above, looked at the source further, this is how it looks like (my webdriver script is trying to tap `name="Ja"` (_Ja_ → _Yes_ in german):

```
                  <XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="AX error -25205" label="AX error -25205" enabled="true" visible="true" x="187" y="373" width="136" height="44">
                    <XCUIElementTypeButton type="XCUIElementTypeButton" value="AX error -25205" name="AX error -25205" label="Ja" enabled="true" visible="true" x="187" y="373" width="136" height="44"/>
                  </XCUIElementTypeOther>
```

but it only finds

```
name="AX error -25205" label="Ja"
```

while that used to be

```
name="Ja" label="Ja"
```

in previous versions of XCode.

As for the other case I mentioned ("`Login.email`"), that works in iOS 9.3, will supply more logs as I get ahold of them.

**Comment by peritus** [comment]
@mykola-mokhnach 

so, had a few more test runs, here is the xml rendering (both with your window_based_xml_source branch, both the same application, but different iOS / phone model):

### iOS 9.3 - iPhone 5s

Automation works beautifully, all the elements are there

```
  <XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="AX error -25205" label=" Willkommen zurück!  Login.email   Login.password  Login.forgotPassword   Login.button[disabled]" enabled="true" visible="true" x="0" y="64" width="375" height="603">
    <XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="AX error -25205" label=" Willkommen zurück!  Login.email   Login.password  Login.forgotPassword  " enabled="true" visible="false" x="0" y="64" width="375" height="0">
      <XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="AX error -25205" label=" Willkommen zurück!  Login.email   Login.password  Login.forgotPassword  " enabled="true" visible="true" x="0" y="64" width="375" height="337">
	<XCUIElementTypeScrollView type="XCUIElementTypeScrollView" value="AX error -25205" name="AX error -25205" label="AX error -25205" enabled="true" visible="true" x="0" y="64" width="375" height="337">
	  <XCUIElementTypeImage type="XCUIElementTypeImage" value="AX error -25205" name="AX error -25205" label="AX error -25205" enabled="true" visible="false" x="369" y="25" width="3" height="36"/>
	  <XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="AX error -25205" label=" Willkommen zurück!  Login.email   Login.password  Login.forgotPassword" enabled="true" visible="true" x="0" y="64" width="375" height="327">
	    <XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="AX error -25205" label=" Willkommen zurück! " enabled="true" visible="true" x="0" y="64" width="375" height="158">
	      <XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="AX error -25205" enabled="true" visible="true" x="152" y="64" width="71" height="70">
		<XCUIElementTypeImage type="XCUIElementTypeImage" value="AX error -25205" name="AX error -25205" label="AX error -25205" enabled="true" visible="true" x="152" y="64" width="71" height="70"/>
	      </XCUIElementTypeOther>
	      <XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="AX error -25205" label="Willkommen zurück! " enabled="true" visible="true" x="49" y="134" width="278" height="88">
		<XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="AX error -25205" name="AX error -25205" label="Willkommen zurück!" enabled="true" visible="true" x="69" y="149" width="238" height="30"/>
		<XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="AX error -25205" name="AX error -25205" enabled="true" visible="false" x="188" y="183" width="0" height="14"/>
	      </XCUIElementTypeOther>
	    </XCUIElementTypeOther>
	    <XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="AX error -25205" label="Login.email   Login.password " enabled="true" visible="true" x="0" y="222" width="375" height="90">
	      <XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="AX error -25205" label="Login.email  " enabled="true" visible="true" x="0" y="222" width="375" height="45">
		<XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="AX error -25205" label="Login.email" enabled="true" visible="true" x="0" y="222" width="375" height="45">
		  <XCUIElementTypeTextField type="XCUIElementTypeTextField" value="Deine E-Mail" name="Login.email" label="Login.email" enabled="true" visible="true" x="15" y="233" width="355" height="22"/>
		</XCUIElementTypeOther>
		<XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="AX error -25205" label=" " enabled="true" visible="true" x="0" y="266" width="375" height="1">
		  <XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="AX error -25205" enabled="true" visible="true" x="0" y="266" width="15" height="1"/>
		  <XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="AX error -25205" enabled="true" visible="true" x="15" y="266" width="360" height="1"/>
		</XCUIElementTypeOther>
	      </XCUIElementTypeOther>
	      <XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="AX error -25205" label="Login.password " enabled="true" visible="true" x="0" y="267" width="375" height="44">
		<XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="AX error -25205" label="Login.password " enabled="true" visible="true" x="0" y="267" width="375" height="44">
		  <XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="AX error -25205" enabled="true" visible="false" x="0" y="267" width="0" height="0"/>
		  <XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="AX error -25205" label="Login.password" enabled="true" visible="true" x="0" y="267" width="375" height="44">
		    <XCUIElementTypeSecureTextField type="XCUIElementTypeSecureTextField" value="Dein Passwort" name="Login.password" label="Login.password" enabled="true" visible="true" x="15" y="278" width="355" height="21"/>
		  </XCUIElementTypeOther>
		</XCUIElementTypeOther>
	      </XCUIElementTypeOther>
	    </XCUIElementTypeOther>
	    <XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="Login.forgotPassword" label="Login.forgotPassword" enabled="true" visible="true" x="0" y="311" width="375" height="80"/>
	  </XCUIElementTypeOther>
	  <XCUIElementTypeImage type="XCUIElementTypeImage" value="AX error -25205" name="AX error -25205" label="AX error -25205" enabled="true" visible="false" x="-39" y="395" width="36" height="3"/>
	</XCUIElementTypeScrollView>
      </XCUIElementTypeOther>
    </XCUIElementTypeOther>
    <XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="AX error -25205" label="Login.button[disabled]" enabled="true" visible="true" x="0" y="401" width="375" height="50">
      <XCUIElementTypeOther type="XCUIElementTypeOther" value="AX error -25205" name="Login.button[disabled]" label="Login.button[disabled]" enabled="true" visible="true" x="0" y="401" width="375" height="50"/>
    </XCUIElementTypeOther>
  </XCUIElementTypeOther>
</XCUIElementTypeOther>
</XCUIElementTypeOther>
</XCUIElementTypeOther>
</XCUIElementTypeOther>
</XCUIElementTypeOther>
```

### iOS 11 - iPhone X

Automation can not find `name="Login.email"` - tests fail

```
<XCUIElementTypeOther type="XCUIElementTypeOther" name=" Willkommen zurück!  Login.email   Login.password  Login.forgotPassword   Login.button[disabled]" label=" Willkommen zurück!  Login.email   Login.password  Login.forgotPassword   Login.button[disabled]" enabled="true" visible="true" x="0" y="88" width="375" height="724">
    <XCUIElementTypeOther type="XCUIElementTypeOther" name="Login.button[disabled]" label="Login.button[disabled]" enabled="true" visible="true" x="0" y="471" width="375" height="50">
      <XCUIElementTypeOther type="XCUIElementTypeOther" name="Login.button[disabled]" label="Login.button[disabled]" enabled="true" visible="true" x="0" y="471" width="375" height="50"/>
    </XCUIElementTypeOther>
  </XCUIElementTypeOther>
</XCUIElementTypeOther>
```

### Notes

* this is a React Native application, so I'm trying to map the XCTest concepts on what I understand how RN maps views to XCUIELements.
* The top level element in both snippets above has `name=" Willkommen zurück!  Login.email   Login.password  Login.forgotPassword   Login.button[disabled]"`, that's why I think they are the representation of the same UI elements. I'm not sure whether this is a feature of XCTest or React Native, but it seems to me that if a XCUElement does not have an explicit `name` it will get one that is a concatenation of all the `name`s of child elements)).
* For the iOS 11 case, the parent element seems to have the proper `name`, but of all the child elements, only the `name=Login.button[disabled]` seems to be visible, all the other elements are missing from the representation (hence my suspicion of a maximum depth in rendering this tree).

@mykola-mokhnach LMK if this is helpful, or whether I can provide more / different info.

**Comment by mykola-mokhnach** [comment]
@peritus Try to get the `format=description` representation of the page source for both cases. I'd like to see how XCTest sees the hierarchy. Also, it will be useful to get the device debug logs for the period while WDA builds the tree. They may contain quite useful information.

**Comment by peritus** [comment]
@mykola-mokhnach Here's the information in a separate gist: https://gist.github.com/peritus/edf951873036342e380115df746aea6d (same application / same setup as before)

**Comment by peritus** [comment]
@mykola-mokhnach I added both the content of `http://localhost:8100/session/3A1824AF-A152-4307-A82A-697FCD76C9F9/source` and `http://localhost:8100/session/3A1824AF-A152-4307-A82A-697FCD76C9F9/source?format=description` to the gist above. There's 6 files in the gist, debug log, format=xml source + format=description source * 2 device configurations

Not knowing too much details, I think this should trigger the line of code you mentioned. If not: Where I can learn how to provide the debug info you need ?

**Comment by mykola-mokhnach** [comment]
That's weird. `http://localhost:8100/session/3A1824AF-A152-4307-A82A-697FCD76C9F9/source?format=description` should provide different output, since it tries to get children windows first and then print their debug descriptions. But here it only prints the description of the application itself, which is useless, since it only contains snapshot addresses in memory.

**Comment by peritus** [comment]
I've now updated to 02887c171699821314c1928642303c36f037ae8a but make sno difference.

<img width="970" alt="screen shot 2018-01-23 at 10 32 57" src="https://user-images.githubusercontent.com/11022/35268246-e2022f34-0028-11e8-8ee4-f898a19dbcc2.png">

**Comment by SamyQAZ** [comment]
There was no issue with Appium inspector on iphon8 (iOS 11.0.2) until yesterday. Since this morning I am unable to launch app using Appium inspector. :disappointed:

Appium inspector logs:
`[2018-01-24 10:32:10][Appium] Requested iOS support with version >= 10, using XCUITest driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
[2018-01-24 10:32:10][Appium] Creating new XCUITestDriver (v2.64.0) session
[2018-01-24 10:32:10][Appium] Capabilities:
[2018-01-24 10:32:10][Appium]   app: /Users/xxx/Downloads/ThePro2-22jan2018.app
[2018-01-24 10:32:10][Appium]   automationName: appium
[2018-01-24 10:32:10][Appium]   bundleId: xxx.xxx.ios
[2018-01-24 10:32:10][Appium]   clearSystemFiles: true
[2018-01-24 10:32:10][Appium]   deviceName: QAiPhone-eight
[2018-01-24 10:32:10][Appium]   fullReset: false
[2018-01-24 10:32:10][Appium]   platformName: iOS
[2018-01-24 10:32:10][Appium]   platformVersion: 11.0.2
[2018-01-24 10:32:10][Appium]   showXcodeLog: true
[2018-01-24 10:32:10][Appium]   udid: 'UDID'
[2018-01-24 10:32:10][Appium]   usePrebuiltWDA: true
[2018-01-24 10:32:10][Appium]   xcodeOrgId: 'OrdId'
[2018-01-24 10:32:10][Appium]   xcodeSigningId: iPhone Developer
[2018-01-24 10:32:10][Appium]   newCommandTimeout: 0
[2018-01-24 10:32:10][Appium]   connectHardwareKeyboard: true
[2018-01-24 10:32:10][BaseDriver] Session created with session id: ed9e00e7-c7ad-46b7-b480-ef8107eb54c2
[2018-01-24 10:32:10][XCUITest] Current user: 'XXX'
[2018-01-24 10:32:11][XCUITest] Current version of libimobiledevice: stable 1.2.0 (bottled), HEAD
[2018-01-24 10:32:11][XCUITest] Xcode version set to '9.2' (tools v9.1.0.0.1.1508540944)
[2018-01-24 10:32:11][XCUITest] iOS SDK Version set to '11.2'
[2018-01-24 10:32:11][BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1516761131523 (10:32:11 GMT+0800 (HKT))
[2018-01-24 10:32:11][XCUITest] Available devices: ce6369d9e302300c0ae0d7e8b3aa9432312d9b00
[2018-01-24 10:32:11][XCUITest] Creating iDevice object with udid 'UDID'
[2018-01-24 10:32:11][XCUITest] Determining device to run tests on: udid: 'UDID', real device: true
[2018-01-24 10:32:11][BaseDriver] Using local app '/Users/xxx/Downloads/ThePro2-22jan2018.app'
[2018-01-24 10:32:11][BaseDriver] Event 'appConfigured' logged at 1516761131702 (10:32:11 GMT+0800 (HKT))
[2018-01-24 10:32:11][XCUITest] Checking whether app '/Users/xxx/Downloads/ThePro2-22jan2018.app' is actually present on file system
[2018-01-24 10:32:11][XCUITest] App is present
[2018-01-24 10:32:11][BaseDriver] Event 'resetStarted' logged at 1516761131704 (10:32:11 GMT+0800 (HKT))
[2018-01-24 10:32:11][XCUITest] Reset: running ios real device reset flow
[2018-01-24 10:32:11][BaseDriver] Event 'resetComplete' logged at 1516761131705 (10:32:11 GMT+0800 (HKT))
[2018-01-24 10:32:11][iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[2018-01-24 10:32:11][iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[2018-01-24 10:32:11][BaseDriver] Event 'logCaptureStarted' logged at 1516761131900 (10:32:11 GMT+0800 (HKT))
[2018-01-24 10:32:11][XCUITest] Setting up real device
[2018-01-24 10:32:12][XCUITest] Reset requested. Removing app with id 'xxx.xxx.ios' from the device
[2018-01-24 10:32:12][XCUITest] Installing '/Users/apple/Downloads/ThePro2-22jan2018.app' on device with UUID 'UDID'...
[2018-01-24 10:32:16][XCUITest] The app has been installed successfully.
[2018-01-24 10:32:16][BaseDriver] Event 'appInstalled' logged at 1516761136727 (10:32:16 GMT+0800 (HKT))
[2018-01-24 10:32:16][XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[2018-01-24 10:32:16][XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[2018-01-24 10:32:16][XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[2018-01-24 10:32:16][JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[2018-01-24 10:32:17][JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.0.2\",\n      \"sdkVersion\" : \"11.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.0.2\",\n      \"ip\" : \"169.254.139.59\"\n    },\n    \"build\" : {\n      \"time\" : \"Jan 18 2018 16:47:00\"\n    }\n  },\n  \"sessionId\" : \"0CB9DD41-D941-4A58-B63C-B63B5A684320\",\n  \"status\" : 0\n}"
[2018-01-24 10:32:17][XCUITest] Will reuse previously cached WDA instance at 'http://localhost:8100/'. Set the wdaLocalPort capability to a value different from 8100 if this is an undesired behavior.
[2018-01-24 10:32:17][BaseDriver] Event 'wdaStartAttempted' logged at 1516761136934 (10:32:16 GMT+0800 (HKT))
[2018-01-24 10:32:17][XCUITest] Using provided WebdriverAgent at 'http://localhost:8100/'
[2018-01-24 10:32:17][BaseDriver] Event 'wdaSessionAttempted' logged at 1516761136935 (10:32:16 GMT+0800 (HKT))
[2018-01-24 10:32:17][XCUITest] Sending createSession command to WDA
[2018-01-24 10:32:17][JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[2018-01-24 10:32:17][JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"11.0.2\",\n      \"sdkVersion\" : \"11.2\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"11.0.2\",\n      \"ip\" : \"169.254.139.59\"\n    },\n    \"build\" : {\n      \"time\" : \"Jan 18 2018 16:47:00\"\n    }\n  },\n  \"sessionId\" : \"0CB9DD41-D941-4A58-B63C-B63B5A684320\",\n  \"status\" : 0\n}"
[2018-01-24 10:32:17][JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"xxx.xxx.ios","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[2018-01-24 10:35:28][JSONWP Proxy] Got response with status 200: {"value":"Failed to launch biz.zwoop.ios application","sessionId":"0CB9DD41-D941-4A58-B63C-B63B5A684320","status":13}
[2018-01-24 10:35:28][XCUITest] Failed to create WDA session. Retrying...
[2018-01-24 10:35:29][BaseDriver] Event 'wdaSessionAttempted' logged at 1516761329176 (10:35:29 GMT+0800 (HKT))
[2018-01-24 10:35:29][XCUITest] Sending createSession command to WDA
[2018-01-24 10:35:29][JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"xxx.xxx.ios","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}`

**Comment by gunnamnandu** [comment]
I am facing same issue, can any one get solution please update

**Comment by SamyQAZ** [comment]
@gunnamnandu It works currently for only one real device in my list. iOS 10.XX still same result 'AX error -25205'
Able to inspect elements on iPhone8(11.0.2) - using Appium.app(1.3.0) and CLI(1.7.2)

**Comment by SenhorCastor** [comment]
Same issue, only works on XCode 9.3 with IOS 11.2.

**Comment by marekcirkos** [comment]
Closing since this is iOS 10.x related issue on Apple side.
