### ISSUE TITLE
Xcodebuild failed with code 65

### ISSUE THREAD

**Issue by VijilPatodi** [facebook/WebDriverAgent#753]
I am facing two issues on real device automation using appium ,below are the configuration which i am using:
Configuration: 
Mac OS:High Sierra(10.13)
Appium : 1.7.1
Xcode: 9
Device: IPhone 6(10.3.2 OS)

1) When I build the xcode solution for webdriverAgent, build successful message is displayed in Xcode however app is not get deployed on device. Why it is not deploying?
2) I deploy the build through terminal (xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=<udid>build test and run the testcases
but facing the issue: Unable to launch webDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Try to remove the webdriver.
PFB more details:
[Appium] Welcome to Appium v1.7.1
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"XCUITest","platformName":"iOS","deviceName":"iPhone","browserName":"safari","udid":"931137575ac1ec0bfccc64530934286bcb07df9b625","xcodeOrgId":"58W2J899ZW","xcodeSigningId":"IPhone Developer","bundleId":"com.stars.WebDriverAgentLib","platformVersion":"10.2.1"}}
[MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","platformName":"iOS","deviceName":"iPhone","browserName":"safari","udid":"931137575ac1ec0bfccc64530934286bcb07df9b625","xcodeOrgId":"58W2J899ZW","xcodeSigningId":"IPhone Developer","bundleId":"com.stars.WebDriverAgentLib","platformVersion":"10.2.1"},null,null]
[BaseDriver] Event 'newSessionRequested' logged at 1507811101206 (17:55:01 GMT+0530 (IST))
[Appium] Creating new XCUITestDriver (v2.51.1) session
[Appium] Capabilities:
[Appium] automationName: 'XCUITest'
[Appium] platformName: 'iOS'
[Appium] deviceName: 'iPhone'
[Appium] browserName: 'safari'
[Appium] udid: '931137575ac1ec0bfccc64530934286bcb07df9b625'
[Appium] xcodeOrgId: '##########'
[Appium] xcodeSigningId: 'IPhone Developer'
[Appium] bundleId: 'com.stars.WebDriverAgentLib'
[Appium] platformVersion: '10.2.1'
[BaseDriver] Session created with session id: 2fe2bc38-b6e1-446f-866b-22a76e001c33
[XCUITest] Xcode version set to '9.0' (tools v9.0.0.0.1.1504363082)
[XCUITest] iOS SDK Version set to '11.0'
[BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1507811102342 (17:55:02 GMT+0530 (IST))
[XCUITest] Available devices: 9337575ac1ec0bfccc64530934286bcb07df9b65
[XCUITest] Creating iDevice object with udid '9337575ac1ec0bfccc64530934286bcb07df9b65'
[XCUITest] Determining device to run tests on: udid: '9337575ac1ec0bfccc64530934286bcb07df9b65', real device: true
[XCUITest] Safari test requested
[BaseDriver] Event 'appConfigured' logged at 1507811103018 (17:55:03 GMT+0530 (IST))
[BaseDriver] Event 'resetStarted' logged at 1507811103018 (17:55:03 GMT+0530 (IST))
[XCUITest] Reset: running ios real device reset flow
[BaseDriver] Event 'resetComplete' logged at 1507811103019 (17:55:03 GMT+0530 (IST))
[iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[BaseDriver] Event 'logCaptureStarted' logged at 1507811103309 (17:55:03 GMT+0530 (IST))
[XCUITest] Setting up real device
[XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Capability 'useNewWDA' set to false, so trying to reuse currently running WDA instance at 'http://localhost:8100/'
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] WDA is not listening at 'http://localhost:8100/'. Rebuilding...
[BaseDriver] Event 'wdaStartAttempted' logged at 1507811104368 (17:55:04 GMT+0530 (IST))
[XCUITest] Launching WebDriverAgent on the device
[XCUITest] Carthage found: '/usr/local/bin/carthage'
[XCUITest] Killing running processes 'xcodebuild.*931137575ac1ec0bfccc64530934286bcb07df9b625, iproxy 8100' for the device 931137575ac1ec0bfccc64530934286bcb07df9b625...
[XCUITest] 'pgrep -nif xcodebuild.*931137575ac1ec0bfccc64530934286bcb07df9b625' didn't detect any matching processes. Return code: 1
[XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB
[XCUITest] Using Xcode 9.0, so fixing WDA codebase
[XCUITest] Generating xcode config file for orgId '58W2J899ZW' and signingId 'IPhone Developer'
[XCUITest] Writing xcode config file to /var/folders/2g/sl90s76d5w1c231gqylsm5kh0000gn/T/2017912-325-1gz457h.ukcoez5mi/appium-temp.xcconfig
[XCUITest] Using Xcode configuration file: '/var/folders/2g/sl90s76d5w1c231gqylsm5kh0000gn/T/2017912-325-1gz457h.ukcoez5mi/appium-temp.xcconfig'
[XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=931137575ac1ec0bfccc64530934286bcb07df9b625IPHONEOS_DEPLOYMENT_TARGET=10.2 -xcconfig /var/folders/2g/sl90s76d5w1c231gqylsm5kh0000gn/T/2017912-325-1gz457h.ukcoez5mi/appium-temp.xcconfig' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Output from xcodebuild will not be logged. To see xcode logging, use 'showXcodeLog' desired capability
[XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[XCUITest] Log file for xcodebuild test: /var/folders/2g/sl90s76d5w1c231gqylsm5kh0000gn/T/com.apple.dt.XCTest/IDETestRunSession-D7CA272D-E95C-490B-B0DA-84716F33C7C0/WebDriverAgentRunner-9A76932F-87F1-40BC-88CE-37E0008E77F8/Session-WebDriverAgentRunner-2017-10-12_175511-JGM4tX.log
[Xcode] 2017-10-12 17:55:11.192 xcodebuild[2994:19896] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/admin/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fd29ebbcb50 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[Xcode] 2017-10-12 17:55:11.192 xcodebuild[2994:19896] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[Xcode] 
[Xcode] ** TEST EXECUTE FAILED **
[Xcode] 
[Xcode] 
[XCUITest] xcodebuild exited with code '65' and signal 'null'
[BaseDriver] Event 'wdaStartFailed' logged at 1507811111204 (17:55:11 GMT+0530 (IST))
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 2993)
[XCUITest] iproxy exited with code 'null'
[XCUITest] Removing WDA application from device
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device. at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:381:13) at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21) at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) at process._tickCallback (internal/process/next_tick.js:103:7) Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device. at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:381:13) at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21) at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) at process._tickCallback (internal/process/next_tick.js:103:7)
[XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[iOSLog] Stopping iOS log capture
[MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device. at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:381:13) at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40) at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22) at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21) at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37) at process._tickCallback (internal/process/next_tick.js:103:7)
[HTTP] <-- POST /wd/hub/session 500 20398 ms - 470 

How can i resolve this issues?

**Comment by nairouz12** [comment]
I'm facing the same issue

**Comment by marekcirkos** [comment]
This to seems to be xcodebuild bug. 
Can you check it it works for random XCUITest and raise an bug with Apple?

**Comment by VTINFOJames** [comment]
I don't believe this is an Xcode bug. The WebDriverAgent needs to be signed with your developer ID in order to install your app onto the device / simulator. Here is the link for what to try per the log you posted:  [](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md).

**Comment by marekcirkos** [comment]
@VTINFOJames, that absolutely makes sense. Thank you!

**Comment by chanugithub** [comment]
I am still getting the same above error, The WebDriverAgent is signed with developer ID and app is also installed in the real device (ios 10.3, xcode 8.3) but unable to launch and throwing the above exact error
[XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device. @VTINFOJames are you able to resolve this issue

**Comment by vikramvi** [comment]
@chanugithub @VijilPatodi refer to solution in https://github.com/appium/appium/issues/9035

**Comment by chanugithub** [comment]
@vikramvi Hi vikram Finally i was able to find the solution, it was actually Apple certificates in key chain access which now i set to 'system default' and previously it was in 'Always trust' mode

**Comment by Jitu1888** [comment]
@vikramvi Which Apple certificates ???

**Comment by vikramvi** [comment]
@chanugithub  can you please clarify per @Jitu1888 comment ?

**Comment by chanugithub** [comment]
@Jitu1888 @vikramvi 
In Mac, 
- Go to Keychain access
- right click on iPhone developer (or your iphone developer ID)
- click on 'get info'
- click on 'Trust' arrow mark
- Observe the first option (when using this certificate: Use 'System Defaults')
- it should be 'System Defaults', it should not be 'Always Trust' or 'never trust'

**Comment by WinterSoldier55** [comment]
@chanugithub all of my certs were set to 'System Defaults', and I'm still seeing this failure

iOS: 11.2.5
Appium: 1.3.2
XCode: 9.2

[info] [Appium] Welcome to Appium v1.7.2
[info] [Appium] Appium REST http interface listener started on 0.0.0.0:4723[info] [HTTP] --> POST /wd/hub/session {"requiredCapabilities":{},"desiredCapabilities":{"deviceName":"SQ iPhone 7","udid":"d4e4e4a5e7d281507501c82a6598f4d1b0ecd5d7","automationName":"XCUITest","xcodeOrdId":"4276V2U4XJ","browserName":"Safari","xcodeSigningId":"iPhone Developer: servicequality.nuance@gmail.com (C7698C8JZ7)","platformVersion":"11.2.5","platformName":"iOS","bundleId":"io.appium.WebDriverAgentRunner-sqtest01"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"deviceName":"SQ iPhone 7","udid":"d4e4e4a5e7d281507501c82a6598f4d1b0ecd5d7","automationName":"XCUITest","xcodeOrdId":"4276V2U4XJ","browserName":"Safari","xcodeSigningId":"iPhone Developer: servicequality.nuance@gmail.com (C7698C8JZ7)","platformVersion":"11.2.5","platformName":"iOS","bundleId":"io.appium.WebDriverAgentRunner-sqtest01"},{},null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1518811298793 (12:01:38 GMT-0800 (PST))
[info] [Appium] Creating new XCUITestDriver (v2.64.0) session
[info] [Appium] Capabilities:
[info] [Appium]   deviceName: SQ iPhone 7
[info] [Appium]   udid: d4e4e4a5e7d281507501c82a6598f4d1b0ecd5d7
[info] [Appium]   automationName: XCUITest
[info] [Appium]   xcodeOrdId: 4276V2U4XJ
[info] [Appium]   browserName: Safari
[info] [Appium]   xcodeSigningId: iPhone Developer: servicequality.nuance@gmail.com (C7698C8JZ7)
[info] [Appium]   platformVersion: 11.2.5
[info] [Appium]   platformName: iOS
[info] [Appium]   bundleId: io.appium.WebDriverAgentRunner-sqtest01
[warn] [BaseDriver] The following capabilities were provided, but are not recognized by appium: xcodeOrdId.
[info] [BaseDriver] Session created with session id: 9c5a76e3-21b3-46f5-8406-5e1764b28a4d
[debug] [XCUITest] Current user: 'servicequality'[debug] [XCUITest] Current version of libimobiledevice: stable 1.2.0 (bottled), HEAD[debug] [XCUITest] Xcode version set to '9.2' (tools v9.2.0.0.1.1510905681)
[debug] [XCUITest] iOS SDK Version set to '11.2'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1518811300232 (12:01:40 GMT-0800 (PST))[debug] [XCUITest] Available devices: d4e4e4a5e7d281507501c82a6598f4d1b0ecd5d7
[debug] [XCUITest] Creating iDevice object with udid 'd4e4e4a5e7d281507501c82a6598f4d1b0ecd5d7'
[info] [XCUITest] Determining device to run tests on: udid: 'd4e4e4a5e7d281507501c82a6598f4d1b0ecd5d7', real device: true
[info] [XCUITest] Safari test requested
[debug] [BaseDriver] Event 'appConfigured' logged at 1518811300394 (12:01:40 GMT-0800 (PST))
[debug] [BaseDriver] Event 'resetStarted' logged at 1518811300394 (12:01:40 GMT-0800 (PST))
[debug] [XCUITest] Reset: running ios real device reset flow
[debug] [BaseDriver] Event 'resetComplete' logged at 1518811300395 (12:01:40 GMT-0800 (PST))
[debug] [iOSLog] Attempting iOS device log capture via libimobiledevice idevicesyslog
[debug] [iOSLog] Starting iOS device log capture with: 'idevicesyslog'
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1518811300636 (12:01:40 GMT-0800 (PST))
[info] [XCUITest] Setting up real device
[info] [XCUITest] Using WDA path: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[info] [XCUITest] Using WDA agent: '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'[debug] [XCUITest] No obsolete cached processes from previous WDA sessions listening on port 8100 have been found
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] WDA is not listening at 'http://localhost:8100/'
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1518811300703 (12:01:40 GMT-0800 (PST))
[info] [XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*d4e4e4a5e7d281507501c82a6598f4d1b0ecd5d7, iproxy 8100' for the device d4e4e4a5e7d281507501c82a6598f4d1b0ecd5d7...
[debug] [XCUITest] 'pgrep -nif xcodebuild.*d4e4e4a5e7d281507501c82a6598f4d1b0ecd5d7' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Starting iproxy to forward traffic from local port 8100 to device port 8100 over USB[debug] [XCUITest] Using Xcode 9.2, so fixing WDA codebase
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=d4e4e4a5e7d281507501c82a6598f4d1b0ecd5d7 IPHONEOS_DEPLOYMENT_TARGET=11.2' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged. To see xcode logging, use 'showXcodeLog' desired capability[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [XCUITest] Log file for xcodebuild test: /var/folders/_s/466dbvqx2_3cs15r0w3gr6nw0000gp/T/com.apple.dt.XCTest/IDETestRunSession-3BBDC227-B8EB-4C4A-BE96-789FD7562D23/WebDriverAgentRunner-A86FEA4F-062D-4A6A-9F2C-E737F763A68F/Session-WebDriverAgentRunner-2018-02-16_120148-DssH2K.log
[info] [Xcode] 2018-02-16 12:01:48.942 xcodebuild[7400:173857] Error Domain=NSCocoaErrorDomain Code=260 "The file “WebDriverAgentRunner-Runner.app” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/servicequality/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app, NSUnderlyingError=0x7fca9ef41da0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
[info] [Xcode] 2018-02-16 12:01:48.942 xcodebuild[7400:173857] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[info] [Xcode] 
[info] [Xcode] ** TEST EXECUTE FAILED **
[info] [Xcode] 
[info] [Xcode] 
[info] [XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1518811308962 (12:01:48 GMT-0800 (PST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[info] [XCUITest] Shutting down sub-processes
[info] [XCUITest] Shutting down iproxy process (pid 7399)
[debug] [XCUITest] iproxy exited with code 'null'
[debug] [XCUITest] Removing WDA application from device[error] [XCUITest] Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
 Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture
[error] [MJSONWP] Encountered internal error running command: Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65". Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at XCUITestDriver.quitAndUninstall$ (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:375:13)
    at tryCatch (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at <anonymous>
[info] [HTTP] <-- POST /wd/hub/session 500 10496 ms - 470

**Comment by chanugithub** [comment]
@WinterSoldier55 the problem is many things, the compiler just displays error 65 which is not good. 

check ur sign in profile and xcode developer id etc
test/run the wda agent runner so that it would be installed in device and then run ur scripts. Folow once again each step in this link
 https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

**Comment by rcuyugan** [comment]
Having the same error. I see the web driver being installed when I build with Xcode. I followed all the configurations on the link provided above. Check my signing profile on Xcode no errors but when I try to launch the inspector on Appium I get the error. BTW, this is my second setup. I have a setup at work that works but I set that up a long time ago and it is running a different version of the Appium desktop. I am trying to set one up at home on my mac.

**Comment by RoakyWood** [comment]
@rcuyugan Did you figure out your Appium issue with the 65 error?
Regards, RW

**Comment by hemasudheer** [comment]
Hi Guys is there a fix or work around for this one ?

**Comment by Arav4prot** [comment]
Hi Guys, I am also facing the same issue. 
https://github.com/appium/appium/issues/11590

I have followed all the guidelines the real-device config link that I have seen but still the issue persists. Can anyone please help on this?

**Comment by narendra-chandratre** [comment]
Hi Team,
Facing same issue.

**Scenario :**
I am able to launch my application on Simulator with iOS version 9.3 But when I am trying to inspect element I am getting error :
**"xcodebuild failed with code 65".**


# Below are my logs:
[debug] [XCUITest] Removing WDA application from device[debug] [BaseDriver] Event 'wdaUninstalled' logged at 1545744128456 (18:52:08 GMT+0530 (IST))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1545744128456 (18:52:08 GMT+0530 (IST))
[info] [XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*9DB129D1-28B4-47A3-AB13-2AA118D672D6, iproxy 8100, 9DB129D1-28B4-47A3-AB13-2AA118D672D6.*XCTRunner' for the device 9DB129D1-28B4-47A3-AB13-2AA118D672D6...
[debug] [XCUITest] 'pgrep -nif xcodebuild.*9DB129D1-28B4-47A3-AB13-2AA118D672D6' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif iproxy 8100' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] 'pgrep -nif 9DB129D1-28B4-47A3-AB13-2AA118D672D6.*XCTRunner' didn't detect any matching processes. Return code: 1
[debug] [XCUITest] Using Xcode 9.2, so fixing WDA codebase
[debug] [XCUITest] Beginning test with command 'xcodebuild test-without-building -project /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=9DB129D1-28B4-47A3-AB13-2AA118D672D6 IPHONEOS_DEPLOYMENT_TARGET=9.3' in directory '/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged. To change this, use 'showXcodeLog' desired capability[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: /var/folders/6_/7sj7myss6gzfg70g73dy905h0000gp/T/com.apple.dt.XCTest/IDETestRunSession-FF883AD1-5886-47D7-9337-1DD41F50F878/WebDriverAgentRunner-1930EB9B-E1C1-428C-A53A-BD484D3FB069/Session-WebDriverAgentRunner-2018-12-25_185211-M4CYnM.log[info] [Xcode] 2018-12-25 18:52:11.665 xcodebuild[39958:1375567] Error Domain=IDEFoundationErrorDomain Code=1 "Cannot launch simulated executable: no file found at /Users/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app" UserInfo={NSLocalizedDescription=Cannot launch simulated executable: no file found at /Users/Library/Developer/Xcode/DerivedData/WebDriverAgent-dikkwtrisltbeobjmfvpthwwekvs/Build/Products/Debug-iphonesimulator/WebDriverAgentRunner-Runner.app}
[info] [Xcode] 2018-12-25 18:52:11.665 xcodebuild[39958:1375567] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}
[info] [Xcode] 
[info] [Xcode] 2018-12-25 18:52:11.667 xcodebuild[39958:1375583] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7fdefd5a3600>
[info] [Xcode] 
[info] [Xcode] ** TEST EXECUTE FAILED **
[info] [Xcode] 
[info] [Xcode] 
[info] [XCUITest] xcodebuild exited with code '65' and signal 'null'
[debug] [BaseDriver] Event 'wdaStartFailed' logged at 1545744131689 (18:52:11 GMT+0530 (IST))
[debug] [XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65".
[debug] [XCUITest] Quitting and uninstalling WebDriverAgent, then retrying
[info] [XCUITest] Shutting down sub-processes
[debug] [XCUITest] Removing WDA application from device[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1545744141896 (18:52:21 GMT+0530 (IST))
[info] [XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Killing running processes 'xcodebuild.*9DB129D1-28B4-47A3-AB13-2AA118D672D6, iproxy 8100, 9DB129D1-28B4-47A3-AB13-2AA118D672D6.*XCTRunner' for the device 9DB129D1-28B4-47A3-AB13-2AA118D672D6...
