### ISSUE TITLE
Can't swipe up to load more!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by tianyig** [facebook/WebDriverAgent#768]
I use swipe function to load more feed, but the speed is very slow, the feed have prepared load,so i can't see load more symbol，Is any way to control swipe speed?

**Comment by tianyig** [comment]
Like flick function operation?

**Comment by marekcirkos** [comment]
You can try drag and drop.

**Comment by lingtingSir** [comment]
Now while you're on this screen - try to get hierarchy view using XCTest - you will see that it triggers loadMore() function even if your screen is at the top (this is because it iterates(?) through all elements and it triggers loadMore() while iterating through some elements at the bottom of screen).
So the cause of this error was that it was loading more and more stuff infinite number of times throwing weird and unrelated errors.

**Comment by lingtingSir** [comment]
https://github.com/facebook/WebDriverAgent/issues/316

**Comment by lingtingSir** [comment]
try to get hierarchy view using XCTest - you will see that it triggers loadMore() ,How to avoid more loads to be triggered

**Comment by lingtingSir** [comment]
@marekcirkos
