### ISSUE TITLE
Run integration tests with Xcode9/iOS11  on Travis

### ISSUE THREAD

**Issue by mykola-mokhnach** [facebook/WebDriverAgent#779]
Currently it's only running on Xcode8.3/iOS10.3 It would be nice to add Xcode9/iOS11 to this set.

**Comment by marekcirkos** [comment]
I am happy to switch, we need to fix integration tests first tho.

**Comment by marekcirkos** [comment]
@mykola-mokhnach I fixed few of them. There are to left to fix.
1) `FBScrollingTests/testSimpleScroll` - Scroll back is much slower, because frames have wrong values and scroll path is calculated badly
2) `XCUIElementFBFindTests_AttributesPage/testInvisibleDescendantWithXPathQuery` visibility changes.

Can you have a look at second one? I'll try to resolve first, WHEN I got some free time :/

**Comment by mykola-mokhnach** [comment]
Visibility detection is a pain. I was thinking about splitting isVisible and isClickable properties, since it is possible that an element, which is visible is not clickable (but not vice versa).

**Comment by mykola-mokhnach** [comment]
From what I [found](https://forums.developer.apple.com/thread/63723) on the internet the `exists` property of XCUIElement is a reflection of its visibility (`hidden`, `alpha` and `opaque` properties of UIView) state and `hittable` shows whether it is clickable. However, I have no idea about how to extract these from a snapshot. 

Also, I see that the properties above were not working properly prior to iOS10 release

**Comment by marekcirkos** [comment]
Fixed
