### ISSUE TITLE
Can we use this to run XCUITests for an app ?

### ISSUE THREAD

**Issue by gop1334** [facebook/WebDriverAgent#86]
Currently we have set of XCUITests written in Swift for our app and we execute them on simulator. If FBSimulatorControl can launch parallel simulators in the same machine, can we use XCTWebDriverAgent to run the tests in parallel in the simulators launched ? Is this doable and if yes how can one do it ? Any information on this would very helpful. Thanks!

**Comment by marekcirkos** [comment]
If you got XCUITests written in swift you don't need XCTWebDriverAgent. XCTWebDriverAgent uses XCUITest to test/automate applications by http instructions (more details check https://code.google.com/p/selenium/wiki/WebDriverForMobileBrowsers). 

Unfortunately you can't run multiple XCUITest in parallel with FBSimulatorControl yet, but we are working on it as we need this for XCTWebDriverAgent as well.

**Comment by lawrencelomax** [comment]
> can we use XCTWebDriverAgent to run the tests in parallel in the simulators launched?

It's not currently possible to do this since there appears to be a daemon process `testmanagerd` running on the mac that prevents multiple tests running concurrently for the current user. It is however possible to setup a simulator using `FBSimulatorControl` and inspect it after launching with `DVTOperation`.

However, being able to run tests in parallel will become more important as `XCTWebDriverAgent` matures.

**Comment by Jonahss** [comment]
Multiple real-devices works though, since they each choose a different port
:)

**Comment by bootstraponline** [comment]
What about refactoring the lib so it can be used by people writing XCTest directly? Features like `XCUIElement+FBIsVisible.h` are generally useful regardless if webdriver is used or not. It'd expand the potential contributor base to include everyone using XCTest.

**Comment by Jonahss** [comment]
Kinda of like a separate framework, something like FacebookXCTestUtils?

**Comment by bootstraponline** [comment]
Yep.

**Comment by marekcirkos** [comment]
I don't think we have anything useful except for `scrollToVisible`, which I bet Apple will implement soon. Also instead of using `isFBVisible` you can simply use Apple's `isHittable`. We use `isFBVisible`, because we need it on `FBElementSnapshot`, which is faster to construct element tree etc.

**Comment by bootstraponline** [comment]
> I don't think we have anything useful except for scrollToVisible, which I bet Apple will implement soon.

Pretty much all the `XCTWebDriverAgentLib` commands are useful. Given the state of XCTest, I don't think waiting for Apple to implement things is realistic. 

> Also instead of using isFBVisible you can simply use Apple's isHittable. We use isFBVisible, because we need it on FBElementSnapshot, which is faster to construct element tree etc.

I'm working with the [XCElementSnapshots produced by xcodebuild test](http://michele.io/test-logs-in-xcode) and isHittable isn't available on snapshots. isFBVisible would be useful to know what elements on the snapshots are visible. There isn't another way.

Here are some more examples:

- [hasKeyboardFocus](https://github.com/facebook/WebDriverAgent/blob/6f0cc0f11fa86f88bcd3009a487a2f7bd11d3431/XCTWebDriverAgentLib/Commands/FBElementCommands.m) is used to remove flakiness around typeText. That's a private API and painful to use without something like `XCTWebDriverAgentLib`
- acceptAlertWithApplication/dismissAlertWithApplication - Again implemented with private APIs. Alerts are generally useful and it'd be difficult to replicate without the Facebook lib.
- dragfromtoforduration - not difficult to reimplement but I can imagine a lot of people not wanting to write their own drag helpers
- clear - generic useful helper for clearing an element (again uses private hasKeyboardFocus API)
- setDeviceOrientation - this actually waits for the orientation change to finish before returning which is what most people expect the Apple API to do already

There are a bunch more. In general I think most of the functionality in `XCTWebDriverAgentLib` is desirable to anyone using XCTest directly because the Facebook code almost always offers some advantage over the Apple methods (convenience/stability/etc.). The alternative is everyone dealing with class-dump on their own which is a mess.

**Comment by bootstraponline** [comment]
Another example... Apple still doesn't provide a screenshot API.

**Comment by lawrencelomax** [comment]
>  Another example... Apple still doesn't provide a screenshot API.
There's possibly multiple ways of getting to this:
1) You should checkout [Michele Titolito's post on screenshots in XCTest activity log](http://michele.io/test-logs-in-xcode) they contain screenshots taken before and after interactions with the UI.
2) I hope to land Framebuffer support in `FBSimulatorControl` soon, which will [provide an API for taking screenshots on-demand, or periodically](https://github.com/facebook/FBSimulatorControl/pull/150).

As far as breaking out implementations into a separate library or Framework I can certainly see the benefit. I'm sure that PRs would be appreciated!

**Comment by bootstraponline** [comment]
> As far as breaking out implementations into a separate library or Framework I can certainly see the benefit. I'm sure that PRs would be appreciated!

Cool. I'll try working on this then.

**Comment by lawrencelomax** [comment]
> Cool. I'll try working on this then.

cc @marekcirkos does this sound reasonable? I assumed much of the reason to not break these functions out was based upon your priorities rather being against breaking out implementations to other classes within the repo.

**Comment by marekcirkos** [comment]
I am definitely not against, I thought it is not worth it. As @bootstraponline pointed out it is more useful than I thought :)

**Comment by bootstraponline** [comment]
I've successfully linked XCTWebDriverAgentLib into my XCUITest target and invoked FBElementCommands.typeText.

Is [there a better way](https://github.com/bootstraponline/WebDriverAgent/commit/ab26be414f7eee098a5176a21be510f1cfe75696) to build a universal (`i386 armv7 x86_64 arm64`) version of libXCTWebDriverAgentLib.a?

I'm thinking the helper methods (like typeText) would be better in a Framework with headers instead of a static library?

**Comment by bootstraponline** [comment]
When I pull `typeText` into a new XCTHelper framework, I keep seeing this error:

> ld: symbol(s) not found for architecture x86_64

It's the same kind of error I saw with `libXCTWebDriverAgentLib.a` For some reason the build is setup to produce either arm or x86 and won't produce a universal binary.

**Comment by marekcirkos** [comment]
Probably you need to link XCTest & Accessibility Framework

**Comment by bootstraponline** [comment]
>  What symbols are missing?

The missing symbols were for XCTest (since XCTestDriver is used in typeText).

> Probably you need to link XCTest & Accessibility Framework.

You're right. I updated Other Linker Flags to include those and now it compiles.

<img width="766" alt="other_linker_flags" src="https://cloud.githubusercontent.com/assets/1173057/12855733/1668a500-cc0f-11e5-8c3e-3e6c733c6be2.png">

I didn't see that in the other targets so not sure how they link with XCTest.

**Comment by claire020326** [comment]
@marekcirkos @lawrencelomax  A follow-up on this issue. Just wondering is there any progress on making XCUITest parallel with FBSimulatorControl?

**Comment by marekcirkos** [comment]
You can start WDA with `FBSimulatorControl`. Just check out our [wiki](https://github.com/facebook/WebDriverAgent/wiki/Starting-WebDriverAgent)

**Comment by marekcirkos** [comment]
Ok, I finished extracting code that could be used to write regular XCUITests, so closing :)

**Comment by Catrinacen** [comment]
hi @Jonahss , do you mean we can start multiple WDA servers on one single iphone?

> Multiple real-devices works though, since they each choose a different port
:)
