### ISSUE TITLE
Include snapshot.identifier in tree output & inspector

### ISSUE THREAD

**Issue by bootstraponline** [facebook/WebDriverAgent#94]
WebDriverAgent sets name to wdName in `FBDebugCommands.m` which makes it impossible to tell if an accessibility identifier has been used. The accessibility label is set to name when there's no accessibility identifier. Labels aren't great to use for automation because they'll change depending on the locale. It'd be great if WebDriverAgent supported `info[@"identifier"] = ValueOrNull(snapshot.identifier);` as an independent attribute.

**Comment by marekcirkos** [comment]
We set label as name when name is not set, because this is how `UIAutomation` works. It allows smoother switch from `UIAutomation` to `XCUITest`. I think that as `XCUITest`, becomes more 'complete' we should start removing such 'smoothers' (also UIA class mapping etc.). However till then, we definitely can and another parameter to tree and inspector that returns raw identifier.

**Comment by bootstraponline** [comment]
awesome! this will be excellent for teams using XCUITest directly but still relying on facebook's inspector.

**Comment by marekcirkos** [comment]
Ok, implemented in on XCTWebDriverAgent, UIAutomation WDA is not modified anyway.

**Comment by bootstraponline** [comment]
Thanks!
