### ISSUE TITLE
Is this project being maintained? 

### ISSUE THREAD

**Issue by saim80** [facebook/WebDriverAgent#974]
I noticed a lot of issues. I also try to create test cases relying on this project and having some issues. I'm on the verge of discontinuation of Appium approach. I'd like to know if the issues will ever be addressed.

**Comment by marekcirkos** [comment]
Yes this project is maintained however not actively worked on. A lot of opened issues require deep investigation on how XCTest work in narrowed edge cases, which is very time expensive. Since I have very limited time I can dedicate to this project, I hope that OpenSource community can help with them a bit. If there are any major issues that blocks our production, I try to fix them asap.

**Comment by saim80** [comment]
@marekcirkos Got it. Thanks for the clarification.

**Comment by vikramvi** [comment]
@marekcirkos am sure facebook has enough money to hire more engineers to maintain this critical project which is being used by millions of automation engineers across globe.

Kindly convey this urgency to your managers to allocate more budget for this important project.

Thanks in advance.

**Comment by vikramvi** [comment]
the last commit done on this project is almost 1 month back which means it's not actively maintained and because of that many engineers across globe are blocked doing their regular tasks.

Facebook can show more commitment and budget for this project
